name: Provision the network
on:
   workflow_dispatch:
    inputs:
      validator_count:
        description: Number of validators to deploy
        default: 2
        type: number
jobs:
  deploy:
    name: Provision
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Configure GCP Credentials
        uses: google-github-actions/auth@v2	
        with:
         credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
         project_id: injective-core
      # Setup chain-stresser
      - name: Checkout chain-stresser
        uses: actions/checkout@master
        with:
          repository: InjectiveLabs/chain-stresser
          token: ${{ secrets.GH_TOKEN }}
          path: ./chain-stresser
          fetch-depth: 0
      - name: Build chain-stresser
        run: |
          cd chain-stresser
          make install
        env:
          GOARCH: amd64
          GOOS: linux
      - name: Checkout starnet
        uses: actions/checkout@master
        with:
         repository: InjectiveLabs/injective-starnet
         token: ${{ secrets.GH_TOKEN }}
         path: ./injective-starnet
      - name: Pulumi up
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: InjectiveLabs/injective-starnet/starnet
          work-dir: ./injective-starnet
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}